from .viewAdmin import *
from .viewAlergia import *
from .viewAnt_Quirurjico import *
from .viewAnt_Transfusional import *
from .viewGeneral import *
from .viewGraficar import *
from .viewHorario import *
from .viewPacientes import *
from .viewPatologia import *
from .viewPerfilClinico import *
from .viewToxicomania import *
from .viewVacuna import *