# Generated by Django 5.0.3 on 2024-04-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloPrincipal', '0002_especialidades_asignacion_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoComida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEsp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.especialista')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verduras', models.IntegerField()),
                ('frutas', models.IntegerField()),
                ('cereales', models.IntegerField()),
                ('leguminosas', models.IntegerField()),
                ('origenAni', models.IntegerField()),
                ('leche', models.IntegerField()),
                ('grasas', models.IntegerField()),
                ('azucares', models.IntegerField()),
                ('idMenu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloNutricion.menu')),
                ('tipoComida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comidas', to='moduloNutricion.tipocomida')),
            ],
        ),
    ]
