# Generated by Django 5.0.3 on 2024-05-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloNutricion', '0002_menu_bien'),
        ('moduloPrincipal', '0003_alter_diagnostico_id_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_bien',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='moduloPrincipal.cita'),
        ),
    ]
