# Generated by Django 5.0.3 on 2024-06-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloNutricion', '0004_menu_bien_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('porcion', models.FloatField()),
                ('peso', models.TextField()),
                ('peso_neto', models.TextField()),
                ('energia', models.TextField()),
                ('proteina', models.TextField()),
                ('lipidos', models.TextField()),
                ('carbos', models.TextField()),
                ('ag_satur', models.TextField()),
                ('ag_mono', models.TextField()),
                ('ag_poli', models.TextField()),
                ('colesterol', models.TextField()),
                ('azucar', models.TextField()),
                ('fibra', models.TextField()),
                ('vita_A', models.TextField()),
                ('aci_asc', models.TextField()),
                ('aci_foli', models.TextField()),
                ('calcio', models.TextField()),
                ('hierro', models.TextField()),
                ('potasio', models.TextField()),
                ('sodio', models.TextField()),
                ('fosforo', models.TextField()),
                ('etanol', models.TextField()),
                ('ig', models.TextField()),
                ('carga_gli', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloNutricion.tipo')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloNutricion.unidad')),
            ],
        ),
    ]
