# Generated by Django 5.0.3 on 2024-06-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloNutricion', '0005_tipo_unidad_alimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='tipo',
            new_name='tipo_nombre',
        ),
    ]
