# Generated by Django 5.0.6 on 2024-06-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloNutricion', '0002_menu_menu'),
        ('moduloNutricion', '0006_rename_tipo_tipo_tipo_nombre'),
    ]

    operations = [
    ]
