# Generated by Django 5.0.3 on 2024-03-27 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('estatus', models.CharField(max_length=1)),
                ('imagen', models.ImageField(default='', upload_to='imagenes_citas')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('exploracion_fisica', models.CharField(default='si', max_length=2)),
                ('diagnostico_tratamiento', models.CharField(default='si', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('creatinina', models.FloatField(default=0)),
                ('genero', models.CharField(default='M', max_length=1)),
                ('estado_civil', models.CharField(max_length=1)),
                ('estilo_vida', models.CharField(max_length=1)),
                ('estatus', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ruta_doc', models.FileField(default='', upload_to='Historiales')),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=8)),
                ('info_ad', models.TextField()),
                ('horario', models.TextField()),
                ('estatus', models.CharField(max_length=1)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.especialidades')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.especialista'),
        ),
        migrations.CreateModel(
            name='Exploracion_fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('glucosa', models.IntegerField()),
                ('TA_sistolica', models.CharField(max_length=20)),
                ('TA_diastolica', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('descripcion', models.TextField()),
                ('imc', models.FloatField(default=0.0)),
                ('creatinina', models.FloatField(default=0.0)),
                ('filtracion_glomerular', models.FloatField(default=0.0)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Historiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_doc', models.FileField(default='', upload_to='Historiales')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente'),
        ),
        migrations.CreateModel(
            name='Ant_transfusionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('tiempo', models.FloatField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Ant_quirurjicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('tiempo', models.FloatField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Ant_Patologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=1)),
                ('id_especialista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.especialista')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Toxicomania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=20)),
                ('frecuencia', models.CharField(max_length=20)),
                ('tiempo', models.FloatField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='imagenes_usuario')),
                ('tipo', models.CharField(default='P', max_length=1)),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.usuario'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.usuario'),
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.IntegerField()),
                ('año', models.IntegerField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moduloPrincipal.paciente')),
            ],
        ),
    ]
