# Generated by Django 5.0.3 on 2024-05-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPrincipal', '0002_especialidades_asignacion_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosticos', to='moduloPrincipal.cita'),
        ),
        migrations.AlterField(
            model_name='exploracion_fisica',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exploraciones', to='moduloPrincipal.cita'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tratamientos', to='moduloPrincipal.cita'),
        ),
    ]
